[target.aarch64-linux-android]
linker = "/home/shashank/ndk/android-ndk-r27/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"

[target.armv7-linux-androideabi]
linker = "/home/shashank/ndk/android-ndk-r27/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang"

[target.i686-linux-android]
linker = "/home/shashank/ndk/android-ndk-r27/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android21-clang"
